---
- name: Install MySQL, Nginx, Samba, PHP-FPM and Mount external Device
  hosts: all
  remote_user: pi
  become: yes
  become_method: sudo

  roles:
    - common
    - php-fpm
    - mysql
    - nginx
    - composer
    - samba
    - mount
    - {role: 'imagetools', tags: 'imagetools'}
    - {role: 'nodejs', tags: 'nodejs'}
