mount_user: pi
mount_group: sambapi
mount_path: /media/medienschubse/
additional_disks:
- disk: /dev/sda
  number: 1
  state: present
  part_start: "0%"
  part_end: "100%"
  fstype: ext4
  mount_state: mounted
  mount_opts: noatime
