---
- name: install mysql
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server-10.0
    - mariadb-client-10.0
    - php7.2-mysql

- name: Create the .my.cnf file
  template: src=.my.cnf dest=/home/pi/.my.cnf
