---
- name: Create the bash-script to sort images
  template: src=imageSortByYearAndMonth.sh dest=/home/pi/imageSortByYearAndMonth.sh

#- name: add the ffmpeg PPA
#  apt_repository:
#    repo: 'ppa:jonathonf/ffmpeg-3'

- name: install imagetools
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - graphicsmagick
    - ffmpeg
    - exiftool

- name: configure npm add global directory
  file:
    state: directory
    path: ~/.npm-global
    mode: 0775

- name: configure npm set prefix to global directory
  command: npm config set prefix '~/.npm-global'

- name: Add a line to user profile file for npm path
  lineinfile:
    path: ~/.profile
    line: export PATH=~/.npm-global/bin:$PATH
    create: yes

# command: LZZ_COMPAT=1 npm install -g thumbsup --unsafe-perm
- name: Node.js | Install thumbsup (static media gallery)
  command: npm install -g thumbsup --unsafe-perm

- name: Creates directory
  file:
    state: directory
    path: "/var/www/html/gallery"
    owner: pi
    group: "www-data"
    mode: 0775
